[2025-09-29 16:37:56] [ERROR] Authentication failed in function 'authenticate' at line 44: (access_denied) 
[2025-09-29 16:39:43] [INFO] New token obtained via OAuth flow
[2025-09-29 16:39:56] [INFO] Loaded existing token
